from __future__ import annotations

OPENAI_API_KEY_ENV = "OPENAI_API_KEY"
OPENAI_MODEL_ENV = "OPENAI_MODEL"
NOTION_TOKEN_ENV = "NOTION_TOKEN"
NOTION_DATABASE_ID_ENV = "NOTION_DATABASE_ID"
NOTION_DATABASE_URL_ENV = "NOTION_DATABASE_URL"
NOTION_VERSION_ENV = "NOTION_VERSION"

DEFAULT_NOTION_VERSION = "2022-06-28"
DEFAULT_OPENAI_MODEL = "gpt-4o-mini"

PROPERTY_RECORD_ID = "지출 항목 고유 식별자"
PROPERTY_SPENT_AT = "지출날짜"
PROPERTY_AMOUNT = "지출 금액"
PROPERTY_CATEGORY = "소비 카테고리"
PROPERTY_SOURCE = "입력 경로"
PROPERTY_BUDGET_STATUS = "예산 평가 결과"
PROPERTY_NOTION_SYNC_STATUS = "Notion 기록 결과"
PROPERTY_OCR_SUMMARY = "OCR 원문 요약"
PROPERTY_OCR_TEXT = "OCR 원문"
PROPERTY_MERCHANT = "상점명"
PROPERTY_PAYMENT_METHOD = "결제수단"
PROPERTY_ADDRESS = "주소"
PROPERTY_PHONE = "전화번호"
PROPERTY_REG_DATE = "등록일시"

STATUS_SUCCESS = "성공"
STATUS_PENDING = "대기"
